# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    container_name: password_strength_backend
    ports:
      - "5000:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=True
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks.celery_tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
